# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orchestrator

import flatbuffers

class AuthRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAuthRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AuthRequest()
        x.Init(buf, n + offset)
        return x

    # AuthRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def AuthRequestStart(builder): builder.StartObject(0)
def AuthRequestEnd(builder): return builder.EndObject()
