# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orchestrator

import flatbuffers

class AuthRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAuthRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AuthRequest()
        x.Init(buf, n + offset)
        return x

    # AuthRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AuthRequest
    def AccessToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def AuthRequestStart(builder): builder.StartObject(1)
def AuthRequestAddAccessToken(builder, accessToken): builder.PrependUint64Slot(0, accessToken, 0)
def AuthRequestEnd(builder): return builder.EndObject()
