# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orchestrator

import flatbuffers

class DDLCreateTableResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDDLCreateTableResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DDLCreateTableResponse()
        x.Init(buf, n + offset)
        return x

    # DDLCreateTableResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DDLCreateTableResponse
    def TableSchema(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .TableSchema import TableSchema
            obj = TableSchema()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def DDLCreateTableResponseStart(builder): builder.StartObject(1)
def DDLCreateTableResponseAddTableSchema(builder, tableSchema): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(tableSchema), 0)
def DDLCreateTableResponseEnd(builder): return builder.EndObject()
