# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orchestrator

import flatbuffers

class DMLDistributedResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDMLDistributedResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DMLDistributedResponse()
        x.Init(buf, n + offset)
        return x

    # DMLDistributedResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DMLDistributedResponse
    def Responses(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .DMLResponse import DMLResponse
            obj = DMLResponse()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DMLDistributedResponse
    def ResponsesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def DMLDistributedResponseStart(builder): builder.StartObject(1)
def DMLDistributedResponseAddResponses(builder, responses): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(responses), 0)
def DMLDistributedResponseStartResponsesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def DMLDistributedResponseEnd(builder): return builder.EndObject()
