# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orchestrator

import flatbuffers

class DMLResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDMLResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DMLResponse()
        x.Init(buf, n + offset)
        return x

    # DMLResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DMLResponse
    def Token(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

def DMLResponseStart(builder): builder.StartObject(1)
def DMLResponseAddToken(builder, token): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(token), 0)
def DMLResponseEnd(builder): return builder.EndObject()
