# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orchestrator

class MessageType(object):
    DDL = 0
    DML = 1
    DDL_CREATE_TABLE = 2
    DDL_DROP_TABLE = 3
    AuthOpen = 4
    AuthClose = 5

