# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gdf

class gdf_dtype(object):
    GDF_invalid = 0
    GDF_INT8 = 1
    GDF_INT16 = 2
    GDF_INT32 = 3
    GDF_INT64 = 4
    GDF_FLOAT32 = 5
    GDF_FLOAT64 = 6
    GDF_DATE32 = 7
    GDF_DATE64 = 8
    GDF_TIMESTAMP = 9
    GDF_CATEGORY = 10
    GDF_STRING = 11
    GDF_STRING_CATEGORY = 12
    N_GDF_TYPES = 13

