# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gdf

import flatbuffers

class gdf_dtype_extra_info(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsgdf_dtype_extra_info(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = gdf_dtype_extra_info()
        x.Init(buf, n + offset)
        return x

    # gdf_dtype_extra_info
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # gdf_dtype_extra_info
    def TimeUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def gdf_dtype_extra_infoStart(builder): builder.StartObject(1)
def gdf_dtype_extra_infoAddTimeUnit(builder, timeUnit): builder.PrependInt8Slot(0, timeUnit, 0)
def gdf_dtype_extra_infoEnd(builder): return builder.EndObject()
