# automatically generated by the FlatBuffers compiler, do not modify

# namespace: interpreter

import flatbuffers

class DMLRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDMLRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DMLRequest()
        x.Init(buf, n + offset)
        return x

    # DMLRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DMLRequest
    def LogicalPlan(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # DMLRequest
    def TableGroup(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .TableGroup import TableGroup
            obj = TableGroup()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def DMLRequestStart(builder): builder.StartObject(2)
def DMLRequestAddLogicalPlan(builder, logicalPlan): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(logicalPlan), 0)
def DMLRequestAddTableGroup(builder, tableGroup): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(tableGroup), 0)
def DMLRequestEnd(builder): return builder.EndObject()
