# automatically generated by the FlatBuffers compiler, do not modify

# namespace: interpreter

import flatbuffers

class ExecutePlanResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsExecutePlanResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExecutePlanResponse()
        x.Init(buf, n + offset)
        return x

    # ExecutePlanResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExecutePlanResponse
    def ResultToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ExecutePlanResponse
    def ConnectionInfo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .NodeConnectionInformation import NodeConnectionInformation
            obj = NodeConnectionInformation()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ExecutePlanResponseStart(builder): builder.StartObject(2)
def ExecutePlanResponseAddResultToken(builder, resultToken): builder.PrependUint64Slot(0, resultToken, 0)
def ExecutePlanResponseAddConnectionInfo(builder, connectionInfo): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(connectionInfo), 0)
def ExecutePlanResponseEnd(builder): return builder.EndObject()
