# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gdf

class gdf_dtype(object):
    GDF_invalid = 0
    GDF_INT8 = 1
    GDF_INT16 = 2
    GDF_INT32 = 3
    GDF_INT64 = 4
    GDF_UINT8 = 5
    GDF_UINT16 = 6
    GDF_UINT32 = 7
    GDF_UINT64 = 8
    GDF_FLOAT32 = 9
    GDF_FLOAT64 = 10
    GDF_DATE32 = 11
    GDF_DATE64 = 12
    GDF_TIMESTAMP = 13
    N_GDF_TYPES = 14

