# automatically generated by the FlatBuffers compiler, do not modify

# namespace: interpreter

import flatbuffers

class GetResultRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGetResultRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GetResultRequest()
        x.Init(buf, n + offset)
        return x

    # GetResultRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GetResultRequest
    def ResultToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def GetResultRequestStart(builder): builder.StartObject(1)
def GetResultRequestAddResultToken(builder, resultToken): builder.PrependUint64Slot(0, resultToken, 0)
def GetResultRequestEnd(builder): return builder.EndObject()
