# automatically generated by the FlatBuffers compiler, do not modify

# namespace: interpreter

class MessageType(object):
    ExecutePlan = 0
    GetResult = 1
    FreeResult = 2
    CloseConnection = 3
    RegisterFileSystem = 4
    DeregisterFileSystem = 5
    LoadCsvSchema = 6
    LoadParquetSchema = 7
    ExecutePlanFileSystem = 8
    FreeMemory = 9
    RegisterDaskSlice = 10

