# automatically generated by the FlatBuffers compiler, do not modify

# namespace: interpreter

class MessageType(object):
    ExecutePlan = 0
    GetResult = 1
    FreeResult = 2
    CloseConnection = 3
    RegisterFileSystem = 4
    DeregisterFileSystem = 5
    LoadCSV = 6
    LoadParquet = 7
    DML_FS = 8

