# automatically generated by the FlatBuffers compiler, do not modify

# namespace: interpreter

import flatbuffers

class NodeConnectionInformation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsNodeConnectionInformation(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NodeConnectionInformation()
        x.Init(buf, n + offset)
        return x

    # NodeConnectionInformation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NodeConnectionInformation
    def Path(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # NodeConnectionInformation
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def NodeConnectionInformationStart(builder): builder.StartObject(2)
def NodeConnectionInformationAddPath(builder, path): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(path), 0)
def NodeConnectionInformationAddType(builder, type): builder.PrependInt8Slot(1, type, 0)
def NodeConnectionInformationEnd(builder): return builder.EndObject()
