# automatically generated by the FlatBuffers compiler, do not modify

# namespace: protocol

import flatbuffers

class Header(object):
    __slots__ = ['_tab']

    # Header
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Header
    def MessageType(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Header
    def PayloadLength(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # Header
    def SessionToken(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))

def CreateHeader(builder, messageType, payloadLength, sessionToken):
    builder.Prep(8, 24)
    builder.PrependUint64(sessionToken)
    builder.PrependUint64(payloadLength)
    builder.Pad(7)
    builder.PrependInt8(messageType)
    return builder.Offset()
