# automatically generated by the FlatBuffers compiler, do not modify

# namespace: authorization

import flatbuffers

class AuthResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAuthResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AuthResponse()
        x.Init(buf, n + offset)
        return x

    # AuthResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AuthResponse
    def AccessToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def AuthResponseStart(builder): builder.StartObject(1)
def AuthResponseAddAccessToken(builder, accessToken): builder.PrependUint64Slot(0, accessToken, 0)
def AuthResponseEnd(builder): return builder.EndObject()
