# automatically generated by the FlatBuffers compiler, do not modify

# namespace: calcite

import flatbuffers

class DDLDropTableRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDDLDropTableRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DDLDropTableRequest()
        x.Init(buf, n + offset)
        return x

    # DDLDropTableRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DDLDropTableRequest
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DDLDropTableRequest
    def DbName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def DDLDropTableRequestStart(builder): builder.StartObject(2)
def DDLDropTableRequestAddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def DDLDropTableRequestAddDbName(builder, dbName): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(dbName), 0)
def DDLDropTableRequestEnd(builder): return builder.EndObject()
