# automatically generated by the FlatBuffers compiler, do not modify

# namespace: calcite

import flatbuffers

class DDLResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDDLResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DDLResponse()
        x.Init(buf, n + offset)
        return x

    # DDLResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def DDLResponseStart(builder): builder.StartObject(0)
def DDLResponseEnd(builder): return builder.EndObject()
