# automatically generated by the FlatBuffers compiler, do not modify

# namespace: calcite

import flatbuffers

class DMLResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDMLResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DMLResponse()
        x.Init(buf, n + offset)
        return x

    # DMLResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DMLResponse
    def LogicalPlan(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # DMLResponse
    def Time(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def DMLResponseStart(builder): builder.StartObject(2)
def DMLResponseAddLogicalPlan(builder, logicalPlan): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(logicalPlan), 0)
def DMLResponseAddTime(builder, time): builder.PrependInt64Slot(1, time, 0)
def DMLResponseEnd(builder): return builder.EndObject()
