# automatically generated by the FlatBuffers compiler, do not modify

# namespace: io

import flatbuffers

class CommunicationNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCommunicationNode(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CommunicationNode()
        x.Init(buf, n + offset)
        return x

    # CommunicationNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CommunicationNode
    def Buffer(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # CommunicationNode
    def BufferAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # CommunicationNode
    def BufferLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def CommunicationNodeStart(builder): builder.StartObject(1)
def CommunicationNodeAddBuffer(builder, buffer): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(buffer), 0)
def CommunicationNodeStartBufferVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def CommunicationNodeEnd(builder): return builder.EndObject()
