# automatically generated by the FlatBuffers compiler, do not modify

# namespace: io

import flatbuffers

class FileSystemRegisterRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFileSystemRegisterRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FileSystemRegisterRequest()
        x.Init(buf, n + offset)
        return x

    # FileSystemRegisterRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FileSystemRegisterRequest
    def Authority(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FileSystemRegisterRequest
    def Root(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FileSystemRegisterRequest
    def FileSystemConnectionType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FileSystemRegisterRequest
    def FileSystemConnection(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def FileSystemRegisterRequestStart(builder): builder.StartObject(4)
def FileSystemRegisterRequestAddAuthority(builder, authority): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(authority), 0)
def FileSystemRegisterRequestAddRoot(builder, root): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(root), 0)
def FileSystemRegisterRequestAddFileSystemConnectionType(builder, fileSystemConnectionType): builder.PrependUint8Slot(2, fileSystemConnectionType, 0)
def FileSystemRegisterRequestAddFileSystemConnection(builder, fileSystemConnection): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(fileSystemConnection), 0)
def FileSystemRegisterRequestEnd(builder): return builder.EndObject()
