# automatically generated by the FlatBuffers compiler, do not modify

# namespace: io

import flatbuffers

class POSIX(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPOSIX(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = POSIX()
        x.Init(buf, n + offset)
        return x

    # POSIX
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def POSIXStart(builder): builder.StartObject(0)
def POSIXEnd(builder): return builder.EndObject()
