# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gdf

class gdf_time_unit(object):
    TIME_UNIT_NONE = 0
    TIME_UNIT_s = 1
    TIME_UNIT_ms = 2
    TIME_UNIT_us = 3
    TIME_UNIT_ns = 4

